{
  "resourceType": "ValueSet",
  "id": "2.16.840.1.113883.3.3616.200.110.102.6080",
  "meta": {
    "versionId": "5",
    "lastUpdated": "2020-08-18T10:21:27.000-04:00"
  },
  "url": "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.3616.200.110.102.6080",
  "version": "20200710",
  "name": "COVID19 SNOMED Value Set for Coronavirus Infections, Excluding SARS CoV 2",
  "status": "active",
  "date": "2020-07-10T01:00:55-04:00",
  "publisher": "Clinical Architecture",
  "compose": {
    "include": [
      {
        "system": "http://snomed.info/sct",
        "version": "http://snomed.info/sct/731000124108/version/20220301",
        "concept": [
          {
            "code": "12591000132100",
            "display": "Suspected severe acute respiratory syndrome (situation)"
          },
          {
            "code": "12601000132105",
            "display": "Probable severe acute respiratory syndrome (situation)"
          },
          {
            "code": "186747009",
            "display": "Coronavirus infection (disorder)"
          },
          {
            "code": "186758000",
            "display": "Coronavirus as the cause of diseases classified to other chapters (disorder)"
          },
          {
            "code": "187467005",
            "display": "[X]Coronavirus infection, unspecified (disorder)"
          },
          {
            "code": "27619001",
            "display": "Disease caused by Coronaviridae (disorder)"
          },
          {
            "code": "441590008",
            "display": "Pneumonia caused by Severe acute respiratory syndrome coronavirus (disorder)"
          },
          {
            "code": "700217006",
            "display": "Suspected coronavirus infection (situation)"
          },
          {
            "code": "713084008",
            "display": "Pneumonia caused by Human coronavirus (disorder)"
          }
        ]
      }
    ]
  }
}