{
  "resourceType" : "ValueSet",
  "id" : "2.16.840.1.113883.10.20.5.9.40",
  "meta" : {
    "versionId" : "20",
    "lastUpdated" : "2021-04-07T01:00:18.000-04:00"
  },
  "url" : "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.10.20.5.9.40",
  "version" : "20210407",
  "name" : "NHSN COVID19 Case Classification",
  "status" : "active",
  "date" : "2021-04-07T01:00:18-04:00",
  "publisher" : "CDC NHSN",
  "compose" : {
    "include" : [{
      "system" : "http://snomed.info/sct",
      "version" : "http://snomed.info/sct/731000124108/version/20220301",
      "concept" : [{
        "code" : "1240591000000102",
        "display" : "Severe acute respiratory syndrome coronavirus 2 not detected (finding)"
      },
      {
        "code" : "840539006",
        "display" : "Disease caused by Severe acute respiratory syndrome coronavirus 2 (disorder)"
      }]
    }]
  },
  "expansion" : {
    "identifier" : "urn:uuid:97804699-ea00-447d-8698-b115a2c78672",
    "timestamp" : "2022-09-27T23:08:33-04:00",
    "total" : 2,
    "offset" : 0,
    "parameter" : [{
      "name" : "count",
      "valueInteger" : 1000
    },
    {
      "name" : "offset",
      "valueInteger" : 0
    }],
    "contains" : [{
      "system" : "http://snomed.info/sct",
      "version" : "http://snomed.info/sct/731000124108/version/20220301",
      "code" : "1240591000000102",
      "display" : "Severe acute respiratory syndrome coronavirus 2 not detected (finding)"
    },
    {
      "system" : "http://snomed.info/sct",
      "version" : "http://snomed.info/sct/731000124108/version/20220301",
      "code" : "840539006",
      "display" : "Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"
    }]
  }
}