{
  "resourceType": "ValueSet",
  "id": "2.16.840.1.113762.1.4.1032.114",
  "meta": {
    "versionId": "5",
    "lastUpdated": "2020-04-10T01:00:18.000-04:00"
  },
  "url": "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1032.114",
  "version": "20200410",
  "name": "C19HCC Confirmed COVID19 Infection SNOMEDCT",
  "status": "active",
  "date": "2020-04-10T01:00:18-04:00",
  "publisher": "MITRE Steward",
  "compose": {
    "include": [
      {
        "system": "http://snomed.info/sct",
        "version": "http://snomed.info/sct/731000124108/version/20220301",
        "concept": [
          {
            "code": "840539006",
            "display": "Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"
          }
        ]
      }
    ]
  },
  "expansion": {
    "identifier": "urn:uuid:31f3df19-dedf-4442-a4f0-a1b13aba3d94",
    "timestamp": "2022-09-27T18:36:53-04:00",
    "total": 1,
    "offset": 0,
    "parameter": [
      {
        "name": "count",
        "valueInteger": 1000
      },
      {
        "name": "offset",
        "valueInteger": 0
      }
    ],
    "contains": [
      {
        "system": "http://snomed.info/sct",
        "version": "http://snomed.info/sct/731000124108/version/20220301",
        "code": "840539006",
        "display": "Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"
      }
    ]
  }
}