{
  "resourceType" : "ValueSet",
  "id" : "2.16.840.1.113762.1.4.1032.117",
  "meta" : {
    "versionId" : "5",
    "lastUpdated" : "2020-04-10T01:00:18.000-04:00"
  },
  "url" : "http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1032.117",
  "version" : "20200410",
  "name" : "C19HCC Confirmed COVID19 Infection",
  "status" : "active",
  "date" : "2020-04-10T01:00:18-04:00",
  "publisher" : "MITRE Steward",
  "compose" : {
    "include" : [{
      "valueSet" : ["http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1032.110"]
    },
    {
      "valueSet" : ["http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1032.114"]
    },
    {
      "valueSet" : ["http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1032.105"]
    }]
  },
  "expansion" : {
    "identifier" : "urn:uuid:b146e352-26ee-47ae-a501-d48f872c82d7",
    "timestamp" : "2022-09-27T18:36:48-04:00",
    "total" : 3,
    "offset" : 0,
    "parameter" : [{
      "name" : "count",
      "valueInteger" : 1000
    },
    {
      "name" : "offset",
      "valueInteger" : 0
    }],
    "contains" : [{
      "system" : "http://snomed.info/sct",
      "version" : "http://snomed.info/sct/731000124108/version/20220301",
      "code" : "840539006",
      "display" : "Disease caused by severe acute respiratory syndrome coronavirus 2 (disorder)"
    },
    {
      "system" : "http://hl7.org/fhir/sid/icd-10-cm",
      "version" : "2023",
      "code" : "B97.29",
      "display" : "Other coronavirus as the cause of diseases classified elsewhere"
    },
    {
      "system" : "http://hl7.org/fhir/sid/icd-10-cm",
      "version" : "2023",
      "code" : "U07.1",
      "display" : "COVID-19"
    }]
  }
}